version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: financas_postgres
    restart: always
    environment:
      POSTGRES_USER: financas_user
      POSTGRES_PASSWORD: financas_password
      POSTGRES_DB: financas_gestao
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local